//
// LocationWeather.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LocationWeather: Codable {

    public var consolidatedWeather: [Weather]?
    public var title: String?
    public var locationType: String?
    public var woeid: Int?
    public var time: String?
    public var sunRise: String?
    public var sunSet: String?

    public init(consolidatedWeather: [Weather]?, title: String?, locationType: String?, woeid: Int?, time: String?, sunRise: String?, sunSet: String?) {
        self.consolidatedWeather = consolidatedWeather
        self.title = title
        self.locationType = locationType
        self.woeid = woeid
        self.time = time
        self.sunRise = sunRise
        self.sunSet = sunSet
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case consolidatedWeather = "consolidated_weather"
        case title
        case locationType = "location_type"
        case woeid
        case time
        case sunRise = "sun_rise"
        case sunSet = "sun_set"
    }

}
