//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

 struct Location: Codable, Identifiable {

    var title: String?
    var locationType: String?
    let id: Int
    var lattLong: String?

    init(title: String?, locationType: String?, id: Int, lattLong: String?) {
        self.title = title
        self.locationType = locationType
        self.id = id
        self.lattLong = lattLong
    }

     enum CodingKeys: String, CodingKey, CaseIterable { 
        case title
        case locationType = "location_type"
        case id = "woeid"
        case lattLong = "latt_long"
    }
}
