//
// GetLocationDataAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class GetLocationDataAPI {
    /**
     Get location data
     
     - parameter woeid: (path)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getLocationData(woeid: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: LocationWeather?,_ error: Error?) -> Void)) {
        getLocationDataWithRequestBuilder(woeid: woeid).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get location data
     - GET /api/location/{woeid}/
     - parameter woeid: (path)  
     - returns: RequestBuilder<LocationWeather> 
     */
    open class func getLocationDataWithRequestBuilder(woeid: String) -> RequestBuilder<LocationWeather> {
        var path = "/api/location/{woeid}/"
        let woeidPreEscape = "\(APIHelper.mapValueToPathItem(woeid))"
        let woeidPostEscape = woeidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{woeid}", with: woeidPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<LocationWeather>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
